server:
  port: 3001

#eureka:
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${random.uuid}
#  client:
#    service-url:
#      default-zone: http://localhost:8761/eureka/
#    fetch-registry: true
#    register-with-eureka: true

spring:
  rabbitmq:
    host: host.docker.internal
    username: guest
    password: guest
    port: 5672
  application:
    name: remote-code-execution-client-service
#  config:
#    import: optional:configserver:config-server
#  cloud:
#    config:
#      discovery:
#        enabled: true
#        service-id: config-server