server:
  port: ${PORT:3001}
hostname: ${HOSTNAME:localhost:3001}
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka

spring:
  application:
    name: remote-code-execution-client-service
  rabbitmq:
    host:  ${RABBITMQ_URL}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

jwt:
  header: Authorization
  secret:  ${JWT_SECRET}
  expiration: 86400

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.assignment: DEBUG